_target_: experiments.eventgen.wrappers.LGATrSlimCFM

net:
 _target_: lgatr.LGATrSlim

 in_v_channels: null
 in_s_channels: null
 out_v_channels: 1
 out_s_channels: null
 hidden_v_channels: 32
 hidden_s_channels: 64

 num_blocks: 6
 num_heads: 8
 mlp_ratio: 2
 attn_ratio: 2

defaults:
 - framesnet: identity
