_target_: experiments.tagging.wrappers.HybridCGENNLGATrWrapper
out_channels: null              # init_physics -> num_outputs 

net:
  _target_: experiments.baselines.olfaithful.HybridCGENNLGATr
  _partial_: true
  in_s_channels: null          #should be 
  # num_classes is supplied by the wrapper at call time (= out_channels)

  hidden_mv_channels: 16
  hidden_s_channels: 32
  num_blocks: 10
  num_heads: 8
  head_scale: true
  checkpoint_blocks: false

  k: 16
  cgenn_layers: 3
  cgenn_hidden_h: 72
  cgenn_hidden_x: 16
  cgenn_aggregation: mean
  cgenn_residual: true
  cgenn_layer_type: fc
  cgenn_normalization_init: 0
  concat_original: true
  use_explicit_edge_features: true

  beam_spurion: xyplane
  add_time_spurion: true
  beam_mirror: true
  knn_metric: minkowski

defaults:
  - framesnet: identity
