exp_type: toptagging
exp_name: topt_local_debug

data:
 boost_jet: true
 data_dir: data
 dataset: full

defaults:
 - training: top_transformer
 - tagging
 - override model: tag_top_transformer
 - _self_
